"""update freebies table

Revision ID: 0eae55610338
Revises: 73091216e364
Create Date: 2025-03-04 15:46:56.004399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eae55610338'
down_revision = '73091216e364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('value', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dev_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_freebies_Company_id_companies'), 'companies', ['Company_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_freebies_dev_id_devs'), 'devs', ['dev_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_freebies_dev_id_devs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_freebies_Company_id_companies'), type_='foreignkey')
        batch_op.drop_column('Company_id')
        batch_op.drop_column('dev_id')
        batch_op.drop_column('value')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
