"""Create freebies table

Revision ID: 73091216e364
Revises: 5f72c58bf48c
Create Date: 2025-03-04 08:02:46.412765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73091216e364'
down_revision = '5f72c58bf48c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freebies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freebies')
    # ### end Alembic commands ###
