"""Fixed Company model

Revision ID: ea0e0e1d288b
Revises: ee770768b537
Create Date: 2025-03-10 12:15:11.920352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0e0e1d288b'
down_revision = 'ee770768b537'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
